version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: skywalker2023
      MYSQL_DATABASE: wordpress
      MYSQL_USER: kenobi
      MYSQL_PASSWORD: yoda
    
  wordpress:
    depends_on:
      - db
    image: starwars_wordpress
    build:
        context: .
        dockerfile: ./startwars-wordpress-file
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: kenobi
      WORDPRESS_DB_PASSWORD: yoda
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}
  wordpress_data: {}

